version: '3.8'

services:
  jibayat_app:
    build: .
    container_name: jibayat_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - dokploy-network
    volumes:
      - jibayat_db:/app/data
      - jibayat_uploads:/app/uploads
      - jibayat_exports:/app/static/exports
    environment:
      - FLASK_ENV=production

volumes:
  jibayat_db:
  jibayat_uploads:
  jibayat_exports:

networks:
  dokploy-network:
    external: true
